engine_api_url = "http://plasma-execution:8551"
consensus_api_host = "0.0.0.0"
authrpc_jwtsecret = "/node/jwt.hex"

[persistence]
data_dir = "/node/consensus"

[network]
interval = 5
p2p_port = 34070
timeout = 5
identity_file_path = "/node/consensus/ec-secp256k1-non-validator.der"

[api]
enabled = true
host = "127.0.0.1"
port = 35070

[committee_bls_pub_keys]
[committee_bls_pub_keys.0]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-0.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-0.hex"

[committee_bls_pub_keys.1]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-1.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-1.hex"

[committee_bls_pub_keys.2]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-2.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-2.hex"

[committee_bls_pub_keys.3]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-3.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-3.hex"

[committee_bls_pub_keys.4]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-4.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-4.hex"

[committee_bls_pub_keys.5]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-5.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-5.hex"

[committee_bls_pub_keys.6]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-6.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-6.hex"

[committee_bls_pub_keys.7]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-7.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-7.hex"

[committee_bls_pub_keys.8]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-8.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-8.hex"

[committee_bls_pub_keys.9]
validator_keystore_pk_file_path = "/node/keys/bls12-381-public-key-9.hex"
identity_file_path = "/node/identities/ec-secp256k1-validator-public-compressed-9.hex"

[bootstrap_nodes.0]
api_host = "plasma-testnet-observer-cs-0.plasmalabs.tech"
p2p_port = 34070
peer_id = "16Uiu2HAm6MP8mzeveHCEvKabcvFZuHSVVN6q5mLYeFow53sB9mBc"

[bootstrap_nodes.1]
api_host = "plasma-testnet-observer-cs-1.plasmalabs.tech"
p2p_port = 34070
peer_id = "16Uiu2HAm2LipxgPhTzL63vGBa4vvq8hjBTvHLL5JpQJEnnndoB8b"

[bootstrap_nodes.2]
api_host = "plasma-testnet-observer-cs-2.plasmalabs.tech"
p2p_port = 34070
peer_id = "16Uiu2HAmQei2ekvcimo3sPpfnHMW52NUMJsD9os3Ek38iDxtpEmT"

